### ISSUE TITLE
Permission to use?

### ISSUE THREAD

**Issue by variaatio** [pmvreeswijk/ZOGY#1]
Hi

I'm an Astronomy student in University of Turku and would like to use and modify this implementation for my master thesis work / use it for our research groups work. There doesn't seem to be any publicly noted license etc. mentioned on this code implementation.

Given that It is here publicly on Github I'm interpreting that you meant this to be allowed to be used by others and modified. However I though it would be polite and prudent to verify this directly in case I have misunderstood. So could you please clarify on this matter.

Of course I/we will refer to your implementation and cite you in all our work and papers, when we use your implementation for our research. Also if I do any applicable modifications/patches I will contribute back.

**Comment by pmvreeswijk** [comment]
Hi Ari,

Thanks for your email.

Sure, no problem in using the ZOGY python implementation that I put on Github. Will be happy if you find it useful. It’s still changing a lot these weeks/months, but you’ll see any changes come by. If you have any suggestions for improvements, just let me know.

cheers,
Paul
